# Generated by Django 4.0.2 on 2022-03-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/aussieactive-1brtlzDq-o8-unsplash.jpg', upload_to='images/'),
        ),
    ]
