# Generated by Django 4.0.2 on 2022-03-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='aussieactive-1brtlzDq-o8-unsplash.jpg', upload_to='images/'),
        ),
    ]
