# Generated by Django 4.0.2 on 2022-02-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_namemodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date',
        ),
        migrations.AddField(
            model_name='namemodels',
            name='text',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
