# Generated by Django 4.0.2 on 2022-02-28 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_question_date_namemodels_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nameModels',
        ),
    ]
